name: todolist
description: A TODO list project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.7.1
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.5
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
  build_runner:
  injectable_generator:
  auto_route_generator:

flutter:
  uses-material-design: true
